# Generated by Django 2.0.10 on 2019-01-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='multiplo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
