# Generated by Django 2.0.10 on 2019-01-23 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.Cliente'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.Produto'),
        ),
    ]
