# Generated by Django 2.0.10 on 2019-01-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0006_auto_20190123_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='preco_unit',
            field=models.FloatField(default=False),
        ),
    ]
