# Generated by Django 2.0.10 on 2019-01-24 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0007_auto_20190123_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='multiplo',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='preco_unit',
        ),
    ]
