# Generated by Django 2.0.10 on 2019-01-24 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0008_auto_20190123_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='preco_unit',
            field=models.FloatField(default=False),
        ),
    ]
