# Generated by Django 2.0.10 on 2019-01-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0010_auto_20190123_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='preco_unit',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='qtd',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='preco_unitario',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='quantidade',
            field=models.IntegerField(default=False),
        ),
    ]
