# Generated by Django 2.0.10 on 2019-01-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0011_auto_20190123_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='multiplo',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
