# Generated by Django 2.0.10 on 2019-01-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0012_auto_20190124_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='multiplo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_unit',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
