# Generated by Django 2.0.10 on 2019-01-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0016_auto_20190124_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
