# Generated by Django 2.0.10 on 2019-01-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0018_auto_20190126_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
