# Generated by Django 2.0.10 on 2019-01-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0022_auto_20190127_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='multiplo',
            field=models.IntegerField(default=0),
        ),
    ]
