# Generated by Django 2.0.6 on 2019-02-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0023_auto_20190130_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
