# Generated by Django 2.0.6 on 2019-02-19 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0027_auto_20190219_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pedido.Cliente'),
        ),
    ]
