# Generated by Django 2.0.6 on 2019-02-22 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0029_auto_20190222_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.Cliente'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.Produto'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='preco_unitario',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_unit',
            field=models.FloatField(max_length=200),
        ),
    ]
