# Generated by Django 2.0.6 on 2019-02-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0030_auto_20190222_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
